const ActionTypes = {
    FETCH_CUSTOMERS_REQUEST : "FETCH_CUSTOMERS_REQUEST",
    FETCH_CUSTOMERS_SUCCESS : "FETCH_CUSTOMERS_SUCCESS",
    FETCH_CUSTOMERS_FAILURE : "FETCH_CUSTOMERS_FAILURE",
  
    FETCH_CUSTOMER_REQUEST : "FETCH_CUSTOMER_REQUEST",
    FETCH_CUSTOMER_SUCCESS : "FETCH_CUSTOMER_SUCCESS",
    FETCH_CUSTOMER_FAILURE : "FETCH_CUSTOMER_FAILURE",
  
    CREATE_CUSTOMER_REQUEST : "CREATE_CUSTOMER_REQUEST",
    CREATE_CUSTOMER_SUCCESS : "CREATE_CUSTOMER_SUCCESS",
    CREATE_CUSTOMER_FAILURE : "CREATE_CUSTOMER_FAILURE",
  
    UPDATE_CUSTOMER_REQUEST : "UPDATE_CUSTOMER_REQUEST",
    UPDATE_CUSTOMER_SUCCESS : "UPDATE_CUSTOMER_SUCCESS",
    UPDATE_CUSTOMER_FAILURE : "UPDATE_CUSTOMER_FAILURE",
  
    DELETE_CUSTOMER_REQUEST : "DELETE_CUSTOMER_REQUEST",
    DELETE_CUSTOMER_SUCCESS : "DELETE_CUSTOMER_SUCCESS",
    DELETE_CUSTOMER_FAILURE : "DELETE_CUSTOMER_FAILURE",
  };
  
  export default ActionTypes;
  